### ISSUE TITLE
Captcha doesn't validate letters in Images

### ISSUE THREAD

**Issue by Zeraal** [wbstr/vaadin-recaptcha#6]
Hello.

People of QA in my proyect detect that this kind of captchas (letters in images) doesn't get validated as well as other kind of captchas. they could write anything and the captcha pass. We want to know if is an Issue with you or with google.

![Uploading Captcha 1.jpg . . .]()

**Comment by Zeraal** [comment]
![captcha 1](https://cloud.githubusercontent.com/assets/595324/6954108/af25f90a-d88b-11e4-8b4a-b95c004e9626.jpg)

**Comment by kumm** [comment]
weird.
My code just wraps net.tanesha.recaptcha.ReCaptchaImpl:.isValid for validation.
Maybe something changed at google.

**Comment by juger89** [comment]
I close this issue, because a newer version is available with Recaptcha 2.0 support.
