### ISSUE TITLE
java.net.UnknownHostException: api-verify.recaptcha.net

### ISSUE THREAD

**Issue by nowxue** [wbstr/vaadin-recaptcha#9]
Hi,

I'm getting a java.net.UnknownHostException: api-verify.recaptcha.net when using the component from my server. It was working fine one week ago, but since last couple of days I'm getting this error on my production server, in localhost it works fine with the same key and I generated the key using the server host name. ¿What's changed in the last days? appreciate any help.

**Comment by juger89** [comment]
I close this issue, because a newer version is available with Recaptcha 2.0 support.
